### ISSUE TITLE
webkit-text-stroke support

### ISSUE THREAD

**Issue by nithiz** [googlefonts/lexend#4]
Hey :)

Great font! I use it for many projects.

However the font doesn't really work well when using it with -webkit-text-stroke. 

Any plans on improving this? Thanks!

**Comment by davelab6** [comment]
This is a fundamental issue with variable fonts, where the outline contours are self intersecting (overlapping) in order to smoothly interpolate along various axes like weight and width. 

In order to achieve the intended effect, you can use css to draw the stroked text twice, once with the stroke on a lower z level, and again without a stroke and with the fill color you want, on a higher z level. 

@elliotjaystocks we should explain this in GFK
